#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Show open files by process running
#?? 1.0.0
##?
##? Usage:
##?    show_open_files

docs::eval "$@"

selected=$(ps axc | awk 'NR > 1' | awk '{print substr($0,index($0,$5))}' | sort -u | fzf)

lsof -c "$selected" | awk '{print $9}'



